"""
init

Revision ID: a59716d41abb
Revises:
Create Date: 2024-11-06 12:59:10.855023

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a59716d41abb"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "camera",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_camera")),
        sa.UniqueConstraint("title", name=op.f("uq_camera_title")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("camera")
    # ### end Alembic commands ###
