"""
Create login and password for camera

Revision ID: e09e456d09a7
Revises: a59716d41abb
Create Date: 2025-05-18 12:53:21.830401

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e09e456d09a7"
down_revision: str | None = "a59716d41abb"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("camera", sa.Column("login", sa.String(length=255), nullable=True))
    op.add_column(
        "camera", sa.Column("hashed_password", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("camera", "hashed_password")
    op.drop_column("camera", "login")
    # ### end Alembic commands ###
